name: seqfeaturizer
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - numpy
  - pandas
  - biopython
  - requests
  - tqdm
  - pyfaidx
  - rapidfuzz
  # Optional but recommended if you want to compute FIMO-based features
  - meme
  - pip
  - pip:
      - -e .
